[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "injury address clip success tomorrow stem theme deputy battle whip viable try together young that advice oppose critic beach coin strike coast spawn taste"
